import type { ChangeEvent, Company, Job } from "./types";

export const DATA_AS_OF = "2026-07-23T07:30:00.000Z";

export const seedCompanies: Company[] = [
  {
    id: "company_ataraxis",
    slug: "ataraxis-ai",
    name: "Ataraxis AI",
    domain: "ataraxis.ai",
    description: "AI-powered precision medicine for cancer care.",
    foundedYear: 2023,
    headquarters: "New York, NY",
    employeeRange: "11-50",
    industry: "AI / Precision medicine",
    stage: "Series A",
    fundingMode: "Venture-backed",
    lifecycleStatus: "Active",
    hiringScore: 91,
    evidenceConfidence: 89,
    latestFundingLabel: "$20.4M Series A",
    latestFundingDate: "2025-03-06",
    careersUrl: "https://jobs.ashbyhq.com/ataraxis-ai",
    sourceUrl: "https://ataraxis.ai/about-us/",
    openJobCount: 2,
    lastVerifiedAt: DATA_AS_OF,
  },
  {
    id: "company_cognition",
    slug: "cognition",
    name: "Cognition",
    domain: "cognition.ai",
    description: "The applied AI lab building autonomous software engineering agents.",
    foundedYear: 2023,
    headquarters: "San Francisco, CA",
    employeeRange: "201-500",
    industry: "AI / Developer tools",
    stage: "Growth",
    fundingMode: "Venture-backed",
    lifecycleStatus: "Active",
    hiringScore: 94,
    evidenceConfidence: 96,
    latestFundingLabel: "Growth funding",
    latestFundingDate: null,
    careersUrl: "https://jobs.ashbyhq.com/cognition",
    sourceUrl: "https://cognition.ai/",
    openJobCount: 3,
    lastVerifiedAt: DATA_AS_OF,
  },
  {
    id: "company_conduct",
    slug: "conduct",
    name: "Conduct",
    domain: "conduct.ai",
    description: "AI agents and enterprise software with a newly announced New York hub.",
    foundedYear: 2024,
    headquarters: "London / New York",
    employeeRange: "11-50",
    industry: "AI / Enterprise software",
    stage: "Series A",
    fundingMode: "Venture-backed",
    lifecycleStatus: "Signal watch",
    hiringScore: 88,
    evidenceConfidence: 83,
    latestFundingLabel: "$60M Series A",
    latestFundingDate: "2026-06-17",
    careersUrl: "https://jobs.ashbyhq.com/conduct",
    sourceUrl: "https://www.conduct.ai/",
    openJobCount: 0,
    lastVerifiedAt: DATA_AS_OF,
  },
  {
    id: "company_edison",
    slug: "edison-scientific",
    name: "Edison Scientific",
    domain: "edisonscientific.com",
    description: "AI scientist agents designed to accelerate scientific discovery.",
    foundedYear: 2025,
    headquarters: "San Francisco, CA",
    employeeRange: "11-50",
    industry: "AI / Scientific research",
    stage: "Seed",
    fundingMode: "Venture-backed",
    lifecycleStatus: "Active",
    hiringScore: 96,
    evidenceConfidence: 92,
    latestFundingLabel: "$70M Seed",
    latestFundingDate: "2025-12-18",
    careersUrl: "https://jobs.ashbyhq.com/Edison%20Scientific",
    sourceUrl: "https://www.edisonscientific.com/",
    openJobCount: 2,
    lastVerifiedAt: DATA_AS_OF,
  },
  {
    id: "company_hotplate",
    slug: "hotplate",
    name: "Hotplate",
    domain: "hotplate.com",
    description: "Commerce infrastructure for independent food businesses.",
    foundedYear: 2020,
    headquarters: "San Francisco, CA",
    employeeRange: "1-10",
    industry: "Food tech / Commerce",
    stage: "Early stage",
    fundingMode: "Venture-backed",
    lifecycleStatus: "Active",
    hiringScore: 74,
    evidenceConfidence: 91,
    latestFundingLabel: "Early-stage funding",
    latestFundingDate: null,
    careersUrl: "https://jobs.ashbyhq.com/hotplate",
    sourceUrl: "https://www.hotplate.com/",
    openJobCount: 1,
    lastVerifiedAt: DATA_AS_OF,
  },
];

const makeJob = (
  id: string,
  companyId: string,
  externalId: string,
  title: string,
  roleFamily: string,
  location: string,
  remoteStatus: string,
  employmentType: string,
  compensation: string,
  canonicalUrl: string,
  summary: string
): Job => ({
  id,
  companyId,
  externalId,
  title,
  roleFamily,
  location,
  remoteStatus,
  employmentType,
  compensation,
  canonicalUrl,
  source: "Ashby",
  status: "verified_open",
  firstSeenAt: DATA_AS_OF,
  lastVerifiedAt: DATA_AS_OF,
  closedAt: null,
  summary,
});

export const seedJobs: Job[] = [
  makeJob("job_ataraxis_biostat", "company_ataraxis", "174d414f-cf1f-4ebc-add2-09d835fdb2dd", "Member of Technical Staff, Principal Biostatistician", "Data and research", "New York HQ", "On-site", "Full time", "See posting", "https://jobs.ashbyhq.com/ataraxis-ai/174d414f-cf1f-4ebc-add2-09d835fdb2dd", "Principal biostatistics role on the technical team."),
  makeJob("job_ataraxis_collab", "company_ataraxis", "61deb58b-e5d6-40db-8e8f-6c571bfc0d78", "Research Collaborations Associate", "Operations", "Remote - U.S.", "Remote", "Full time", "See posting", "https://jobs.ashbyhq.com/ataraxis-ai/61deb58b-e5d6-40db-8e8f-6c571bfc0d78", "Research partnership and collaboration operations."),
  makeJob("job_cognition_capture", "company_cognition", "1b2f97f6-2215-4ebd-bd01-4c6a10ca4ac0", "Capture Lead - Federal", "GTM", "Washington, DC", "On-site", "Full time", "See posting", "https://jobs.ashbyhq.com/cognition/1b2f97f6-2215-4ebd-bd01-4c6a10ca4ac0", "Federal capture strategy and cross-functional execution."),
  makeJob("job_cognition_workplace", "company_cognition", "781253e9-294d-4820-b465-dcb00d92476c", "Workplace & Engagement Coordinator", "People operations", "New York City", "On-site", "Full time", "See posting", "https://jobs.ashbyhq.com/cognition/781253e9-294d-4820-b465-dcb00d92476c", "Workplace operations and employee engagement."),
  makeJob("job_cognition_hr", "company_cognition", "3e287a98-b54f-4fe1-a804-32391dfc43fc", "HR Operations", "People operations", "San Francisco", "On-site", "Full time", "See posting", "https://jobs.ashbyhq.com/cognition/3e287a98-b54f-4fe1-a804-32391dfc43fc", "Core HR operations at a fast-growing AI lab."),
  makeJob("job_edison_evals", "company_edison", "d7644e8f-a067-4c69-9d0d-77149ac32f60", "Scientific Evals", "Data and research", "San Francisco", "On-site", "Full time", "$160K-$300K", "https://jobs.ashbyhq.com/Edison%20Scientific/d7644e8f-a067-4c69-9d0d-77149ac32f60", "Build rigorous benchmarks and training datasets for AI science."),
  makeJob("job_edison_gtm", "company_edison", "cc9bd15e-13d3-4d53-aa06-2918362a5b6f", "GTM Strategy & Operations Lead", "Operations", "San Francisco; New York; Remote U.S.", "Hybrid", "Full time", "$200K-$275K", "https://jobs.ashbyhq.com/Edison%20Scientific/cc9bd15e-13d3-4d53-aa06-2918362a5b6f", "Build the commercial operating system for a scaling AI science company."),
  makeJob("job_hotplate_fullstack", "company_hotplate", "0d598ee9-ddfa-472a-945c-acfe5ac8bcaf", "Full Stack Engineer", "Engineering", "San Francisco Office", "On-site", "Full time", "See posting", "https://jobs.ashbyhq.com/hotplate/0d598ee9-ddfa-472a-945c-acfe5ac8bcaf", "Product engineering for independent food businesses."),
];

export const seedChanges: ChangeEvent[] = [
  {
    id: "change_conduct_raise",
    entityType: "company",
    entityId: "company_conduct",
    changeType: "funding_announced",
    title: "Conduct announced a $60M Series A",
    description: "The company also announced plans for a second headquarters in New York.",
    occurredAt: "2026-06-17T12:00:00.000Z",
    sourceUrl: "https://www.conduct.ai/",
  },
  {
    id: "change_edison_raise",
    entityType: "company",
    entityId: "company_edison",
    changeType: "funding_announced",
    title: "Edison Scientific announced a $70M seed round",
    description: "The new funding is paired with a growing U.S. hiring footprint.",
    occurredAt: "2025-12-18T12:00:00.000Z",
    sourceUrl: "https://www.edisonscientific.com/",
  },
  {
    id: "change_cognition_hr",
    entityType: "job",
    entityId: "job_cognition_hr",
    changeType: "job_opened",
    title: "Cognition is hiring for HR Operations",
    description: "The canonical Ashby posting was verified open.",
    occurredAt: DATA_AS_OF,
    sourceUrl: "https://jobs.ashbyhq.com/cognition/3e287a98-b54f-4fe1-a804-32391dfc43fc",
  },
];
