import {
  companyScoreReceipts,
} from "./hiring-score";
import { normalizeSector } from "./types";
import type { ChangeEvent, Company, Job } from "./types";

export const DATA_AS_OF = "2026-07-23T07:30:00.000Z";

const seedCompanyProfiles: Array<
  Omit<Company, "hiringScore" | "evidenceConfidence" | "openJobCount">
> = [
  {
    id: "company_ataraxis",
    slug: "ataraxis-ai",
    name: "Ataraxis AI",
    domain: "ataraxis.ai",
    description: "AI-powered precision medicine for cancer care.",
    foundedYear: 2023,
    headquarters: "New York, NY",
    employeeRange: "11-50",
    industry: "AI / Precision medicine",
    sector: normalizeSector("AI / Precision medicine"),
    stage: "Series A",
    fundingMode: "Venture-backed",
    lifecycleStatus: "Active",
    latestFundingLabel: "$20.4M Series A",
    latestFundingDate: "2025-03-06",
    careersUrl: "https://jobs.ashbyhq.com/ataraxis-ai",
    sourceUrl: "https://ataraxis.ai/about-us/",
    lastVerifiedAt: DATA_AS_OF,
  },
  {
    id: "company_cognition",
    slug: "cognition",
    name: "Cognition",
    domain: "cognition.ai",
    description: "The applied AI lab building autonomous software engineering agents.",
    foundedYear: 2023,
    headquarters: "San Francisco, CA",
    employeeRange: "201-500",
    industry: "AI / Developer tools",
    sector: normalizeSector("AI / Developer tools"),
    stage: "Growth",
    fundingMode: "Venture-backed",
    lifecycleStatus: "Active",
    latestFundingLabel: "Growth funding",
    latestFundingDate: null,
    careersUrl: "https://jobs.ashbyhq.com/cognition",
    sourceUrl: "https://cognition.ai/",
    lastVerifiedAt: DATA_AS_OF,
  },
  {
    id: "company_conduct",
    slug: "conduct",
    name: "Conduct",
    domain: "conduct.ai",
    description: "AI agents and enterprise software with a newly announced New York hub.",
    foundedYear: 2024,
    headquarters: "London / New York",
    employeeRange: "11-50",
    industry: "AI / Enterprise software",
    sector: normalizeSector("AI / Enterprise software"),
    stage: "Series A",
    fundingMode: "Venture-backed",
    lifecycleStatus: "Signal watch",
    latestFundingLabel: "$60M Series A",
    latestFundingDate: "2026-06-17",
    careersUrl: "https://jobs.ashbyhq.com/conduct",
    sourceUrl: "https://www.conduct.ai/",
    lastVerifiedAt: DATA_AS_OF,
  },
  {
    id: "company_edison",
    slug: "edison-scientific",
    name: "Edison Scientific",
    domain: "edisonscientific.com",
    description: "AI scientist agents designed to accelerate scientific discovery.",
    foundedYear: 2025,
    headquarters: "San Francisco, CA",
    employeeRange: "11-50",
    industry: "AI / Scientific research",
    sector: normalizeSector("AI / Scientific research"),
    stage: "Seed",
    fundingMode: "Venture-backed",
    lifecycleStatus: "Active",
    latestFundingLabel: "$70M Seed",
    latestFundingDate: "2025-12-18",
    careersUrl: "https://jobs.ashbyhq.com/Edison%20Scientific",
    sourceUrl: "https://www.edisonscientific.com/",
    lastVerifiedAt: DATA_AS_OF,
  },
  {
    id: "company_hotplate",
    slug: "hotplate",
    name: "Hotplate",
    domain: "hotplate.com",
    description: "Commerce infrastructure for independent food businesses.",
    foundedYear: 2020,
    headquarters: "San Francisco, CA",
    employeeRange: "1-10",
    industry: "Food tech / Commerce",
    sector: normalizeSector("Food tech / Commerce"),
    stage: "Early stage",
    fundingMode: "Venture-backed",
    lifecycleStatus: "Active",
    latestFundingLabel: "Early-stage funding",
    latestFundingDate: null,
    careersUrl: "https://jobs.ashbyhq.com/hotplate",
    sourceUrl: "https://www.hotplate.com/",
    lastVerifiedAt: DATA_AS_OF,
  },
  {
    id: "company_ramp",
    slug: "ramp",
    name: "Ramp",
    domain: "ramp.com",
    description: "Financial operations software for business spending, cards, and expense management.",
    foundedYear: null,
    headquarters: "United States",
    employeeRange: "See company",
    industry: "Financial technology / Business finance",
    sector: normalizeSector("Financial technology / Business finance"),
    stage: "Growth",
    fundingMode: "Venture-backed",
    lifecycleStatus: "Active",
    latestFundingLabel: "$300M funding round",
    latestFundingDate: null,
    careersUrl: "https://jobs.ashbyhq.com/ramp",
    sourceUrl: "https://ramp.com/press",
    lastVerifiedAt: DATA_AS_OF,
  },
  {
    id: "company_watershed",
    slug: "watershed",
    name: "Watershed",
    domain: "watershed.com",
    description: "Climate software for measuring emissions and operating corporate sustainability programs.",
    foundedYear: null,
    headquarters: "United States",
    employeeRange: "See company",
    industry: "Climate technology / Enterprise sustainability",
    sector: normalizeSector("Climate technology / Enterprise sustainability"),
    stage: "Growth",
    fundingMode: "Funding disclosed",
    lifecycleStatus: "Active",
    latestFundingLabel: "Funding disclosed",
    latestFundingDate: null,
    careersUrl: "https://jobs.ashbyhq.com/watershed",
    sourceUrl: "https://watershed.com/",
    lastVerifiedAt: DATA_AS_OF,
  },
  {
    id: "company_vanta",
    slug: "vanta",
    name: "Vanta",
    domain: "vanta.com",
    description: "Trust management software for security, compliance, risk, and continuous controls.",
    foundedYear: null,
    headquarters: "United States",
    employeeRange: "See company",
    industry: "Cybersecurity / Trust management",
    sector: normalizeSector("Cybersecurity / Trust management"),
    stage: "Series D",
    fundingMode: "Venture-backed",
    lifecycleStatus: "Active",
    latestFundingLabel: "$150M Series D",
    latestFundingDate: "2025-07-23",
    careersUrl: "https://jobs.ashbyhq.com/vanta",
    sourceUrl: "https://www.vanta.com/resources/vanta-announces-series-d",
    lastVerifiedAt: DATA_AS_OF,
  },
  {
    id: "company_harvey",
    slug: "harvey",
    name: "Harvey",
    domain: "harvey.ai",
    description: "AI agents and workflow software built for legal and professional services teams.",
    foundedYear: null,
    headquarters: "United States",
    employeeRange: "See company",
    industry: "Legal technology / Enterprise AI",
    sector: normalizeSector("Legal technology / Enterprise AI"),
    stage: "Growth",
    fundingMode: "Venture-backed",
    lifecycleStatus: "Active",
    latestFundingLabel: "$200M growth round",
    latestFundingDate: "2026-03-25",
    careersUrl: "https://jobs.ashbyhq.com/harvey",
    sourceUrl: "https://www.harvey.ai/blog/harvey-raises-growth-round-at-dollar11-billion-valuation-co-led-by-gic-and-sequoia",
    lastVerifiedAt: DATA_AS_OF,
  },
  {
    id: "company_abridge",
    slug: "abridge",
    name: "Abridge",
    domain: "abridge.com",
    description: "Care intelligence software that turns clinical conversations into structured documentation.",
    foundedYear: null,
    headquarters: "United States",
    employeeRange: "See company",
    industry: "Healthcare / Clinical AI",
    sector: normalizeSector("Healthcare / Clinical AI"),
    stage: "Series E",
    fundingMode: "Venture-backed",
    lifecycleStatus: "Active",
    latestFundingLabel: "$300M Series E",
    latestFundingDate: "2025-06-24",
    careersUrl: "https://jobs.ashbyhq.com/abridge",
    sourceUrl: "https://www.abridge.com/blog/series-e",
    lastVerifiedAt: DATA_AS_OF,
  },
  {
    id: "company_higharc",
    slug: "higharc",
    name: "Higharc",
    domain: "higharc.com",
    description: "AI-native homebuilding software spanning design, estimating, sales, and construction.",
    foundedYear: null,
    headquarters: "United States",
    employeeRange: "See company",
    industry: "Real estate technology / Homebuilding",
    sector: normalizeSector("Real estate technology / Homebuilding"),
    stage: "Series C",
    fundingMode: "Venture-backed",
    lifecycleStatus: "Active",
    latestFundingLabel: "$95M Series C",
    latestFundingDate: "2026-06-30",
    careersUrl: "https://jobs.ashbyhq.com/higharc",
    sourceUrl: "https://www.higharc.com/newsroom/higharc-95m-series-c-for-homebuilding-ai",
    lastVerifiedAt: DATA_AS_OF,
  },
  {
    id: "company_suno",
    slug: "suno",
    name: "Suno",
    domain: "suno.com",
    description: "AI music creation software for artists, producers, songwriters, and listeners.",
    foundedYear: null,
    headquarters: "United States",
    employeeRange: "See company",
    industry: "Media and entertainment / Music",
    sector: normalizeSector("Media and entertainment / Music"),
    stage: "Series D",
    fundingMode: "Venture-backed",
    lifecycleStatus: "Active",
    latestFundingLabel: "$400M+ Series D",
    latestFundingDate: "2026-06-03",
    careersUrl: "https://jobs.ashbyhq.com/suno",
    sourceUrl: "https://suno.com/blog/series-d-announcement",
    lastVerifiedAt: DATA_AS_OF,
  },
];

const makeJob = (
  id: string,
  companyId: string,
  externalId: string,
  title: string,
  roleFamily: string,
  location: string,
  remoteStatus: string,
  employmentType: string,
  compensation: string,
  canonicalUrl: string,
  summary: string
): Job => ({
  id,
  companyId,
  externalId,
  title,
  roleFamily,
  location,
  remoteStatus,
  employmentType,
  compensation,
  canonicalUrl,
  source: "Ashby",
  status: "verified_open",
  firstSeenAt: DATA_AS_OF,
  lastVerifiedAt: DATA_AS_OF,
  closedAt: null,
  summary,
});

export const seedJobs: Job[] = [
  makeJob("job_ataraxis_biostat", "company_ataraxis", "174d414f-cf1f-4ebc-add2-09d835fdb2dd", "Member of Technical Staff, Principal Biostatistician", "Data and research", "New York HQ", "On-site", "Full time", "See posting", "https://jobs.ashbyhq.com/ataraxis-ai/174d414f-cf1f-4ebc-add2-09d835fdb2dd", "Principal biostatistics role on the technical team."),
  makeJob("job_ataraxis_collab", "company_ataraxis", "61deb58b-e5d6-40db-8e8f-6c571bfc0d78", "Research Collaborations Associate", "Operations", "Remote - U.S.", "Remote", "Full time", "See posting", "https://jobs.ashbyhq.com/ataraxis-ai/61deb58b-e5d6-40db-8e8f-6c571bfc0d78", "Research partnership and collaboration operations."),
  makeJob("job_cognition_capture", "company_cognition", "1b2f97f6-2215-4ebd-bd01-4c6a10ca4ac0", "Capture Lead - Federal", "GTM", "Washington, DC", "On-site", "Full time", "See posting", "https://jobs.ashbyhq.com/cognition/1b2f97f6-2215-4ebd-bd01-4c6a10ca4ac0", "Federal capture strategy and cross-functional execution."),
  makeJob("job_cognition_workplace", "company_cognition", "781253e9-294d-4820-b465-dcb00d92476c", "Workplace & Engagement Coordinator", "People operations", "New York City", "On-site", "Full time", "See posting", "https://jobs.ashbyhq.com/cognition/781253e9-294d-4820-b465-dcb00d92476c", "Workplace operations and employee engagement."),
  makeJob("job_cognition_hr", "company_cognition", "3e287a98-b54f-4fe1-a804-32391dfc43fc", "HR Operations", "People operations", "San Francisco", "On-site", "Full time", "See posting", "https://jobs.ashbyhq.com/cognition/3e287a98-b54f-4fe1-a804-32391dfc43fc", "Core HR operations at a fast-growing AI lab."),
  makeJob("job_edison_evals", "company_edison", "d7644e8f-a067-4c69-9d0d-77149ac32f60", "Scientific Evals", "Data and research", "San Francisco", "On-site", "Full time", "$160K-$300K", "https://jobs.ashbyhq.com/Edison%20Scientific/d7644e8f-a067-4c69-9d0d-77149ac32f60", "Build rigorous benchmarks and training datasets for AI science."),
  makeJob("job_edison_gtm", "company_edison", "cc9bd15e-13d3-4d53-aa06-2918362a5b6f", "GTM Strategy & Operations Lead", "Operations", "San Francisco; New York; Remote U.S.", "Hybrid", "Full time", "$200K-$275K", "https://jobs.ashbyhq.com/Edison%20Scientific/cc9bd15e-13d3-4d53-aa06-2918362a5b6f", "Build the commercial operating system for a scaling AI science company."),
  makeJob("job_hotplate_fullstack", "company_hotplate", "0d598ee9-ddfa-472a-945c-acfe5ac8bcaf", "Full Stack Engineer", "Engineering", "San Francisco Office", "On-site", "Full time", "See posting", "https://jobs.ashbyhq.com/hotplate/0d598ee9-ddfa-472a-945c-acfe5ac8bcaf", "Product engineering for independent food businesses."),
];

export const seedChanges: ChangeEvent[] = [
  {
    id: "change_conduct_raise",
    entityType: "company",
    entityId: "company_conduct",
    changeType: "funding_announced",
    title: "Conduct announced a $60M Series A",
    description: "The company also announced plans for a second headquarters in New York.",
    occurredAt: "2026-06-17T12:00:00.000Z",
    sourceUrl: "https://www.conduct.ai/",
  },
  {
    id: "change_edison_raise",
    entityType: "company",
    entityId: "company_edison",
    changeType: "funding_announced",
    title: "Edison Scientific announced a $70M seed round",
    description: "The new funding is paired with a growing U.S. hiring footprint.",
    occurredAt: "2025-12-18T12:00:00.000Z",
    sourceUrl: "https://www.edisonscientific.com/",
  },
  {
    id: "change_cognition_hr",
    entityType: "job",
    entityId: "job_cognition_hr",
    changeType: "job_opened",
    title: "Cognition is hiring for HR Operations",
    description: "The canonical Ashby posting was verified open.",
    occurredAt: DATA_AS_OF,
    sourceUrl: "https://jobs.ashbyhq.com/cognition/3e287a98-b54f-4fe1-a804-32391dfc43fc",
  },
];

/**
 * Snapshot totals are derived from the canonical job and change facts above.
 * This keeps seed data honest when a posting is added, closed, or reclassified.
 */
export const seedCompanies: Company[] = seedCompanyProfiles.map((profile) => {
  const openJobCount = seedJobs.filter(
    (job) => job.companyId === profile.id && job.status === "verified_open"
  ).length;
  const provisional: Company = {
    ...profile,
    openJobCount,
    hiringScore: 0,
    evidenceConfidence: 0,
  };
  const scores = companyScoreReceipts(
    provisional,
    seedJobs,
    seedChanges,
    DATA_AS_OF,
    true
  );
  return {
    ...provisional,
    hiringScore: scores.hiring.value,
    evidenceConfidence: scores.evidence.value,
  };
});
