import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const companies = sqliteTable("companies", {
  id: text("id").primaryKey(),
  slug: text("slug").notNull().unique(),
  name: text("name").notNull(),
  domain: text("domain").notNull(),
  description: text("description").notNull(),
  foundedYear: integer("founded_year"),
  headquarters: text("headquarters").notNull(),
  employeeRange: text("employee_range").notNull(),
  industry: text("industry").notNull(),
  sector: text("sector").notNull(),
  stage: text("stage").notNull(),
  fundingMode: text("funding_mode").notNull(),
  lifecycleStatus: text("lifecycle_status").notNull(),
  hiringScore: integer("hiring_score").notNull(),
  evidenceConfidence: integer("evidence_confidence").notNull(),
  latestFundingLabel: text("latest_funding_label").notNull(),
  latestFundingDate: text("latest_funding_date"),
  careersUrl: text("careers_url").notNull(),
  sourceUrl: text("source_url").notNull(),
  openJobCount: integer("open_job_count").notNull(),
  lastVerifiedAt: text("last_verified_at").notNull(),
});

export const jobs = sqliteTable("jobs", {
  id: text("id").primaryKey(),
  companyId: text("company_id").notNull(),
  externalId: text("external_id").notNull(),
  title: text("title").notNull(),
  roleFamily: text("role_family").notNull(),
  location: text("location").notNull(),
  remoteStatus: text("remote_status").notNull(),
  employmentType: text("employment_type").notNull(),
  compensation: text("compensation").notNull(),
  canonicalUrl: text("canonical_url").notNull().unique(),
  source: text("source").notNull(),
  status: text("status").notNull(),
  firstSeenAt: text("first_seen_at").notNull(),
  lastVerifiedAt: text("last_verified_at").notNull(),
  closedAt: text("closed_at"),
  summary: text("summary").notNull(),
});

export const changes = sqliteTable("changes", {
  id: text("id").primaryKey(),
  entityType: text("entity_type").notNull(),
  entityId: text("entity_id").notNull(),
  changeType: text("change_type").notNull(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  occurredAt: text("occurred_at").notNull(),
  sourceUrl: text("source_url").notNull(),
});
